todolist/list/urls.py
from django.urls import path, include
from . import views

app_name = 'list'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('accounts/', include('allauth.urls')),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('delete/<int:task_id>/', views.delete_task_view, name='delete_task'),
    path('update_status/<int:task_id>/', views.update_status_view, name='update_status'),
    path('edit/<int:task_id>/', views.edit_task_view, name='edit_task'),
]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('list/', include('list.urls')),
    path('accounts/', include('allauth.urls')),
]

todolist/list/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    STATUS_CHOICES = (
        ('IN_PROGRESS', 'Em andamento'),
        ('COMPLETED', 'Concluída'),
    )

    title = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='IN_PROGRESS')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class TaskLog(models.Model):
    task = models.OneToOneField(Task, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=100, default='message')

    def __str__(self):
        return self.message

todolist/list/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

todolist/list/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from allauth.account.forms import SignupForm
from allauth.account.views import SignupView
from .forms import TaskForm
from .models import Task, TaskLog

@login_required
def update_status_view(request, task_id):
    task = get_object_or_404(Task, id=task_id)

    task.status = 'concluida'
    task.save()

    task_log = TaskLog.objects.filter(task=task).first()

    if task_log:
        task_log.message = 'Status atualizado'
        task_log.save()
    else:
        TaskLog.objects.create(task=task, message='Status atualizado')

    return redirect('list:home')

def edit_task_view(request, task_id):
    task = get_object_or_404(Task, id=task_id)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('list:home')
    else:
        form = TaskForm(instance=task)

    context = {
        'form': form,
        'task': task
    }

    return render(request, 'taskedit.html', context)

@login_required
def delete_task_view(request, task_id):
    task = get_object_or_404(Task, id=task_id)

    # Excluir o registro de log associado à tarefa (se existir)
    TaskLog.objects.filter(task=task).delete()

    task.delete()

    return redirect('list:home')

class CustomSignupView(SignupView):
    form_class = SignupForm
    template_name = 'register.html'
    success_url = '/list/'

@login_required
def home_view(request):
    user = request.user
    tasks = Task.objects.filter(user=user).order_by('-tasklog__created_at')
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = user
            task.save()
            # Cria um registro de log da criação da tarefa
            TaskLog.objects.create(task=task, message='Tarefa criada')

            return redirect('list:home')

    context = {
        'user': user,
        'tasks': tasks,
        'form': form
    }

    return render(request, 'home.html', context)

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            print(f'O usuário {username} existe.')
            return redirect('/list/')
        else:
            print('Usuário não encontrado ou senha incorreta.')

    return render(request, 'login.html')

def register_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            try:
                form.save(request=request)
                print('Usuário registrado com sucesso.')
                return redirect('/list/')
            except Exception as e:
                print(f'Erro no registro do usuário: {str(e)}')
        else:
            print('Formulário inválido.')
            print(form.errors)
    else:
        form = SignupForm()

    return render(request, 'register.html', {'form': form})

todolist/list/templates/home.html
{% load static %}
{% load bootstrap4 %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<div class="container">
  <h2 class="welcome">Bem-vindo(a)!</h2>
  <p>Você está logado(a) como {{ user.username }}.</p>

  <a href="{% url 'account_logout' %}" class="btn btn-danger">Logout</a>

  <h3 class="task-heading">Suas Tarefas</h3>
  <ul class="task-list">
    {% for task in tasks %}
      <li>
        <strong>Título:</strong> {{ task.title }}<br>
        <strong>Descrição:</strong> {{ task.description }}<br>
        <strong>Data de Criação:</strong> {{ task.tasklog.created_at }}<br>
        <strong>Log:</strong> {{ task.tasklog.message }}<br>
        <strong>Status:</strong> {{ task.get_status_display }}<br>
        <form method="POST" action="{% url 'list:update_status' task.id %}">
          {% csrf_token %}
          <select name="status" class="status-select">
            <option value="IN_PROGRESS" {% if task.status == 'IN_PROGRESS' %}selected{% endif %}>Em andamento</option>
            <option value="COMPLETED" {% if task.status == 'COMPLETED' %}selected{% endif %}>Concluída</option>
          </select>
          <button type="submit" class="update-button">Atualizar Status</button>
        </form>
        <form method="POST" action="{% url 'list:delete_task' task.id %}">
          {% csrf_token %}
          <button type="submit" class="delete-button btn btn-danger">Excluir</button>

        </form>
      </li>
      <a href="{% url 'list:edit_task' task.id %}" class="btn btn-primary">Editar</a>
    {% empty %}
      <li>Nenhuma tarefa encontrada.</li>
    {% endfor %}
  </ul>

  <h3 class="add-task-heading">Adicionar Tarefa</h3>

  <form method="POST" action="{% url 'list:home' %}" class="form-group">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Adicionar</button>
  </form>
</div>
{% endblock %}

todolist/list/templates/login.html
{% load static %}
{% load bootstrap4 %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<div class="container">
  <h2>Login</h2>

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
  {% endif %}

  <form method="POST" action="{% url 'list:login' %}" class="form-group">
    {% csrf_token %}
    <div>
      <label for="id_username">Username:</label>
      <input class = 'form-control' type="text" name="username" id="id_username">
    </div>
    <div>
      <label for="id_password">Password:</label>
      <input type="password" class = 'form-control' name="password" id="id_password">
    </div>
    <button class="btn" type="submit">Login</button>
  </form>
</div>
{% endblock %}

todolist/list/templates/register.html
{% load static %}
{% load bootstrap4 %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<div class="container">
  <h2>Register</h2>
  <form method="POST" action="{% url 'list:register' %}">
    {% csrf_token %}
    <div>
      <label for="id_username">Username:</label>
      <input type="text" class = 'form-control' name="username" id="id_username">
    </div>
    <div>
      <label for="id_email">Email:</label>
      <input type="email" class = 'form-control' name="email" id="id_email">
    </div>
    <div>
      <label for="id_password1">Password:</label>
      <input type="password" class = 'form-control' name="password1" id="id_password1">
    </div>
    <div>
      <label for="id_password2">Confirm Password:</label>
      <input type="password" class = 'form-control' name="password2" id="id_password2">
    </div>
    <button class = 'btn' type="submit">Register</button>
  </form>
</div>
{% endblock %}

todolist/list/templates/taskedit.html
{% load bootstrap4 %}

{% block content %}
  <h2>Editar Tarefa</h2>

  <form method="POST" action="{% url 'list:edit_task' task.id %}" class="form-group">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
{% endblock %}